main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "${API_VERSION}"
author: AUTHOR
description: DESCRIPTION
commands:
  biomemap:
    description: Export world biomes to JSON.
    usage: "/biomemap [world] [cellSize]"
